### ISSUE TITLE
Add these new categories until firebase is setup.

### ISSUE THREAD

**Issue by tdevinda** [CodeLanka/ez-net-app#28]
Received these categories from Damitha. Need to add these to the links.

**පත්තරේ විස්තරේ**
ලංකාදීප
දිනමිණ
රිවිර
තරුණි(Tharunie.lk)
නවලිය

**කෑම වට්ටෝරු**
https://www.youtube.com/channel/UCVz1bXiY1pz6Fz_Osm0YYBA

**මැහුම් ගෙතුම්**
සාරී  හැට්ට
(https://www.youtube.com/results?search_query=saree+blouse+blocks)
ගවුම් මහන්න
https://www.youtube.com/results?search_query=how+to+sew+a+dress

**බණ දහම් හා අනෙකුත් ආගමික විස්තර**
https://www.youtube.com/results?search_query=bana

**ළමා අධ්‍යාපන අත්වැල**
5 වසර
https://www.youtube.com/watch?v=DUWKu6WSoA8&list=PL94ZZLMZi8sXa8CeaJlDZQ6JY2qc7CKiS
e-තක්ෂලාව
http://www.e-thaksalawa.moe.gov.lk/

**අඩු මිලට බඩු මිලදී ගන්න**
http://www.wow.lk/
http://takas.lk/
https://www.daraz.lk/

**විඩියෝ කෝල් ගැනීම**
skype
https://play.google.com/store/apps/details?id=com.skype.raider
Imo
https://play.google.com/store/apps/details?id=com.imo.android.imoim&hl=en

**ගීත අසන්න**
https://www.youtube.com/results?search_query=sinhala+songs

**Comment by agentmilindu** [comment]
@tdevinda I guess now you can add these to the Firebase
