### ISSUE TITLE
Generate the `.gitignore` file using gitignore.io

### ISSUE THREAD

**Issue by iammosespaulr** [CodeLanka/ez-net-app#35]

**Comment by iammosespaulr** [comment]
Gradle
Node
JavaScript
Android
Android Studio
IDL
INI
JSON
Markdown
Objective-C
YAML

**Comment by agentmilindu** [comment]
I guess if you used  `reactnative` as the technology in gitignore.io, it will cover all these technologies.

**Comment by iammosespaulr** [comment]
Thank you

**Comment by agentmilindu** [comment]
Fixed by #38
