### ISSUE TITLE
App takes a long time to show thumbnails

### ISSUE THREAD

**Issue by agentmilindu** [CodeLanka/ez-net-app#40]
Can we show a loading animation while the app is fetching data from Firebase?

**Comment by nushydude** [comment]
@agentmilindu 
I can take this on

**Comment by agentmilindu** [comment]
@nushydude Let's get this done by our Google Code-In students :) You can mentor them on this! :D 
I need we have to optimize the flow too, like caching the fetch results and showing the cached result, while fetching in the background and updating the view once the new results come.

On the other hand, can you check why it takes very long time and see if there are any optimisations we can do?

**Comment by nushydude** [comment]
Get them to use React Native Spinkit library for the loading animation.

**Comment by agentmilindu** [comment]
@nushydude That's awesome!

**Comment by agentmilindu** [comment]
Fixed by #42
