### ISSUE TITLE
Thumbnails not showing up

### ISSUE THREAD

**Issue by vibhavagarwal5** [CodeLanka/ez-net-app#48]
I am not able to see the thumbnails in my app.
I am getting the thumbUri's as : `file:///data/user/0/org.gdgsrilanka.codelanka.eznet/files/RNFetchBlobTmp_7dsn49d9uwkcalwizcfwlk.png` etc etc <br>
This is showing up instead:
![1](https://user-images.githubusercontent.com/23319631/36379228-c6c50b3e-15a3-11e8-864f-f637091c6deb.jpg)
![whatsapp image 2018-02-19 at 18 35 16](https://user-images.githubusercontent.com/23319631/36379229-c8a39fe2-15a3-11e8-82a8-0b4c21d1fd76.jpeg)

**Comment by TheLukaszNs** [comment]
Did you make and changes in code, or you just cloned EzNet?
Also, make sure that you are on the develop branch - because we're creating code here.

> "**It's working for me**"

**Comment by vibhavagarwal5** [comment]
just cloned and npm installed, m already on develop branch @TheLukaszNs

**Comment by TheLukaszNs** [comment]
I did some work on your issue (#47) and get the same problem when the height and width (in `<Image />` component) were set to 0. Check if it's not the problem.
