### ISSUE TITLE
Build Failed "CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by chathuralakmal** [CodeLanka/ez-net-app#5]
Getting this build failed error even i added the native-base and all the dependencies. any idea about it?

** BUILD FAILED **

The following build commands failed:
CpResource /Developer/ez-net-app/node_modules/native-base/Fonts/Andale\ Mono.ttf build/Build/Products/Debug-iphonesimulator/ReactNativeProject.app/Andale\ Mono.ttf
CpResource /Developer/ez-net-app/node_modules/native-base/Fonts/Arial\ Black.ttf build/Build/Products/Debug-iphonesimulator/ReactNativeProject.app/Arial\ Black.ttf
CpResource /Developer/ez-net-app/node_modules/native-base/Fonts/Arial.ttf build/Build/Products/Debug-iphonesimulator/ReactNativeProject.app/Arial.ttf
CpResource /Developer/ez-net-app/node_modules/native-base/Fonts/Comic\ Sans\ MS.ttf build/Build/Products/Debug-iphonesimulator/ReactNativeProject.app/Comic\ Sans\ MS.ttf
(4 failures)

Installing build/Build/Products/Debug-iphonesimulator/ReactNativeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist]

**Comment by agentmilindu** [comment]
Hi @chathuralakmal you are trying to build for iOS, right? I am not personally familiar with iOS development and I could not try out this on iOS. But we'll get more iOS developers, like you, contributing, hope you all can get this solved. I'm not sure if I pushed everything needed for, but I used a commonly available `.gitignore` file for React Native. I'm curious about this issue, let's get this solved!

**Comment by agentmilindu** [comment]
@chathuralakmal  Check this : https://github.com/facebook/react-native/issues/7308#issuecomment-216317248

**Comment by chathuralakmal** [comment]
@agentmilindu  Yes im trying iOS. ill look around more.

**Comment by agentmilindu** [comment]
Hi @chathuralakmal, you could get this solved? I pushed some changes.had to alter the git history a bit, Get a new clone and try now, I could get it build for iOS on Travis CI ( https://travis-ci.org/CodeLanka/ez-net-app/jobs/249045878 )

**Comment by chathuralakmal** [comment]
@agentmilindu I have managed to make the build success by after 'npm install' i upgraded the react native 'react-native upgrade'. but now im getting another run time errors. im still trying to eliminate them one by one. and yes i tried the latest clone. still having same issue. :(

**Comment by chathuralakmal** [comment]
@agentmilindu i made it work by initializing new react-native project and adding existing js files and other dependencies. i guess this method wont be a problem since we are editing JS files.

[ https://www.dropbox.com/s/uv6qfyrkuhaehwx/react-screenshot.png?dl=0](Screenshot)

**Comment by agentmilindu** [comment]
No problem there. Hope now this is solved with your PR #11. Shall we close this issue?

**Comment by chathuralakmal** [comment]
@agentmilindu  Yeah will close it
